// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
#ifndef __BINDINGS_WEBP2_H
#define __BINDINGS_WEBP2_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct webp2_string_t {
  uint8_t*ptr;
  size_t len;
} webp2_string_t;

typedef struct webp2_own_performance_impl_t {
  int32_t __handle;
} webp2_own_performance_impl_t;

typedef struct webp2_borrow_performance_impl_t {
  int32_t __handle;
} webp2_borrow_performance_impl_t;

typedef struct webp2_own_date_t {
  int32_t __handle;
} webp2_own_date_t;

typedef struct webp2_borrow_date_t {
  int32_t __handle;
} webp2_borrow_date_t;

typedef struct {
  bool is_some;
  webp2_string_t val;
} webp2_option_string_t;

typedef struct webp2_new_error_options_t {
  webp2_option_string_t   cause;
} webp2_new_error_options_t;

typedef struct webp2_own_error_t {
  int32_t __handle;
} webp2_own_error_t;

typedef struct webp2_borrow_error_t {
  int32_t __handle;
} webp2_borrow_error_t;

typedef struct {
  bool is_some;
  webp2_new_error_options_t val;
} webp2_option_new_error_options_t;

// Imported Functions from `webp2`
extern webp2_own_performance_impl_t webp2_get_performance(void);
extern void webp2_report_error(webp2_borrow_error_t throwable);
extern double webp2_method_performance_impl_now(webp2_borrow_performance_impl_t self);
extern double webp2_method_get_performance_impl_time_origin(webp2_borrow_performance_impl_t self);
extern double webp2_static_date_now(void);
extern webp2_own_error_t webp2_constructor_error(webp2_string_t *maybe_message, webp2_new_error_options_t *maybe_options);

// Helper Functions

extern void webp2_performance_impl_drop_own(webp2_own_performance_impl_t handle);

extern webp2_borrow_performance_impl_t webp2_borrow_performance_impl(webp2_own_performance_impl_t handle);

extern void webp2_date_drop_own(webp2_own_date_t handle);

extern webp2_borrow_date_t webp2_borrow_date(webp2_own_date_t handle);

void webp2_option_string_free(webp2_option_string_t *ptr);

void webp2_new_error_options_free(webp2_new_error_options_t *ptr);

extern void webp2_error_drop_own(webp2_own_error_t handle);

extern webp2_borrow_error_t webp2_borrow_error(webp2_own_error_t handle);

void webp2_option_new_error_options_free(webp2_option_new_error_options_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void webp2_string_set(webp2_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void webp2_string_dup(webp2_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void webp2_string_dup_n(webp2_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void webp2_string_free(webp2_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
