package wasi-libc:webp2;

world webp2 {
    resource performance {
        now: func() -> f64;
    }
    import performance: get() -> performance;

    resource date {
        now: static func() -> f64;
    }
}
