// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#include "wasi/webp2.h"
#include <stdlib.h>

// Imported Functions from `webp2`

__attribute__((__import_module__("$root"), __import_name__("[static]date.now")))
extern double __wasm_import_webp2_static_date_now(void);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("$root"), __import_name__("[resource-drop]date")))
extern void __wasm_import_webp2_date_drop(int32_t handle);

void webp2_date_drop_own(webp2_own_date_t handle) {
  __wasm_import_webp2_date_drop(handle.__handle);
}

webp2_borrow_date_t webp2_borrow_date(webp2_own_date_t arg) {
  return (webp2_borrow_date_t) { arg.__handle };
}

// Component Adapters

double webp2_static_date_now(void) {
  double ret = __wasm_import_webp2_static_date_now();
  return ret;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_webp2(void);
__attribute__((used))
void __component_type_object_force_link_webp2_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_webp2();
}
