// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
#include "wasi/webp2.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `wasm:js/global`

__attribute__((__import_module__("wasm:js/global"), __import_name__("[method]performance.now")))
extern double __wasm_import_webp2_method_performance_now(int32_t);

__attribute__((__import_module__("wasm:js/global"), __import_name__("[method][get]performance.time-origin")))
extern double __wasm_import_webp2_method_get_performance_time_origin(int32_t);

__attribute__((__import_module__("wasm:js/global"), __import_name__("[get]global-performance")))
extern int32_t __wasm_import_webp2_get_global_performance(void);

__attribute__((__import_module__("wasm:js/global"), __import_name__("[static]date.now")))
extern double __wasm_import_webp2_static_date_now(void);

__attribute__((__import_module__("wasm:js/global"), __import_name__("[constructor]error")))
extern int32_t __wasm_import_webp2_constructor_error(int32_t, uint8_t *, size_t, int32_t, int32_t, uint8_t *, size_t);

__attribute__((__import_module__("wasm:js/global"), __import_name__("report-error")))
extern void __wasm_import_webp2_report_error(int32_t);

__attribute__((__import_module__("wasm:js/global"), __import_name__("[constructor]uint-8-array")))
extern int32_t __wasm_import_webp2_constructor_uint_8_array(int32_t);

__attribute__((__import_module__("wasm:js/global"), __import_name__("[method]uint-8-array.subarray")))
extern int32_t __wasm_import_webp2_method_uint_8_array_subarray(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasm:js/global"), __import_name__("[method]crypto.get-random-values")))
extern void __wasm_import_webp2_method_crypto_get_random_values(int32_t, int32_t, uint8_t *);

__attribute__((__import_module__("wasm:js/global"), __import_name__("[get]global-crypto")))
extern int32_t __wasm_import_webp2_get_global_crypto(void);

// Imported Functions from `wasm:js/console`

__attribute__((__import_module__("wasm:js/console"), __import_name__("log")))
extern void __wasm_import_webp2_console_log(uint8_t *, size_t);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("wasm:js/global"), __import_name__("[resource-drop]performance")))
extern void __wasm_import_webp2_performance_drop(int32_t handle);

void webp2_performance_drop_own(webp2_own_performance_t handle) {
  __wasm_import_webp2_performance_drop(handle.__handle);
}

webp2_borrow_performance_t webp2_borrow_performance(webp2_own_performance_t arg) {
  return (webp2_borrow_performance_t) { arg.__handle };
}

__attribute__((__import_module__("wasm:js/global"), __import_name__("[resource-drop]date")))
extern void __wasm_import_webp2_date_drop(int32_t handle);

void webp2_date_drop_own(webp2_own_date_t handle) {
  __wasm_import_webp2_date_drop(handle.__handle);
}

webp2_borrow_date_t webp2_borrow_date(webp2_own_date_t arg) {
  return (webp2_borrow_date_t) { arg.__handle };
}

void webp2_option_string_free(webp2_option_string_t *ptr) {
  if (ptr->is_some) {
    webp2_string_free(&ptr->val);
  }
}

void webp2_new_error_options_free(webp2_new_error_options_t *ptr) {
  webp2_option_string_free(&ptr->cause);
}

__attribute__((__import_module__("wasm:js/global"), __import_name__("[resource-drop]error")))
extern void __wasm_import_webp2_error_drop(int32_t handle);

void webp2_error_drop_own(webp2_own_error_t handle) {
  __wasm_import_webp2_error_drop(handle.__handle);
}

webp2_borrow_error_t webp2_borrow_error(webp2_own_error_t arg) {
  return (webp2_borrow_error_t) { arg.__handle };
}

__attribute__((__import_module__("wasm:js/global"), __import_name__("[resource-drop]uint-8-array")))
extern void __wasm_import_webp2_uint_8_array_drop(int32_t handle);

void webp2_uint_8_array_drop_own(webp2_own_uint_8_array_t handle) {
  __wasm_import_webp2_uint_8_array_drop(handle.__handle);
}

webp2_borrow_uint_8_array_t webp2_borrow_uint_8_array(webp2_own_uint_8_array_t arg) {
  return (webp2_borrow_uint_8_array_t) { arg.__handle };
}

__attribute__((__import_module__("wasm:js/global"), __import_name__("[resource-drop]crypto")))
extern void __wasm_import_webp2_crypto_drop(int32_t handle);

void webp2_crypto_drop_own(webp2_own_crypto_t handle) {
  __wasm_import_webp2_crypto_drop(handle.__handle);
}

webp2_borrow_crypto_t webp2_borrow_crypto(webp2_own_crypto_t arg) {
  return (webp2_borrow_crypto_t) { arg.__handle };
}

void webp2_option_new_error_options_free(webp2_option_new_error_options_t *ptr) {
  if (ptr->is_some) {
    webp2_new_error_options_free(&ptr->val);
  }
}

void webp2_option_u32_free(webp2_option_u32_t *ptr) {
  if (ptr->is_some) {
  }
}

void webp2_list_u8_free(webp2_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void webp2_string_set(webp2_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void webp2_string_dup(webp2_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void webp2_string_dup_n(webp2_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void webp2_string_free(webp2_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

double webp2_method_performance_now(webp2_borrow_performance_t self) {
  double ret = __wasm_import_webp2_method_performance_now((self).__handle);
  return ret;
}

double webp2_method_get_performance_time_origin(webp2_borrow_performance_t self) {
  double ret = __wasm_import_webp2_method_get_performance_time_origin((self).__handle);
  return ret;
}

webp2_own_performance_t webp2_get_global_performance(void) {
  int32_t ret = __wasm_import_webp2_get_global_performance();
  return (webp2_own_performance_t) { ret };
}

double webp2_static_date_now(void) {
  double ret = __wasm_import_webp2_static_date_now();
  return ret;
}

webp2_own_error_t webp2_constructor_error(webp2_string_t *maybe_message, webp2_new_error_options_t *maybe_options) {
  webp2_option_string_t message;
  message.is_some = maybe_message != NULL;if (maybe_message) {
    message.val = *maybe_message;
  }
  webp2_option_new_error_options_t options;
  options.is_some = maybe_options != NULL;if (maybe_options) {
    options.val = *maybe_options;
  }
  int32_t option;
  uint8_t * option1;
  size_t option2;
  if ((message).is_some) {
    const webp2_string_t *payload0 = &(message).val;
    option = 1;
    option1 = (uint8_t *) (*payload0).ptr;
    option2 = (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  int32_t option10;
  int32_t option11;
  uint8_t * option12;
  size_t option13;
  if ((options).is_some) {
    const webp2_new_error_options_t *payload4 = &(options).val;
    int32_t option7;
    uint8_t * option8;
    size_t option9;
    if (((*payload4).cause).is_some) {
      const webp2_string_t *payload6 = &((*payload4).cause).val;
      option7 = 1;
      option8 = (uint8_t *) (*payload6).ptr;
      option9 = (*payload6).len;
    } else {
      option7 = 0;
      option8 = 0;
      option9 = 0;
    }
    option10 = 1;
    option11 = option7;
    option12 = option8;
    option13 = option9;
  } else {
    option10 = 0;
    option11 = 0;
    option12 = 0;
    option13 = 0;
  }
  int32_t ret = __wasm_import_webp2_constructor_error(option, option1, option2, option10, option11, option12, option13);
  return (webp2_own_error_t) { ret };
}

void webp2_report_error(webp2_borrow_error_t throwable) {
  __wasm_import_webp2_report_error((throwable).__handle);
}

webp2_own_uint_8_array_t webp2_constructor_uint_8_array(uint32_t length) {
  int32_t ret = __wasm_import_webp2_constructor_uint_8_array((int32_t) (length));
  return (webp2_own_uint_8_array_t) { ret };
}

webp2_own_uint_8_array_t webp2_method_uint_8_array_subarray(webp2_borrow_uint_8_array_t self, uint32_t begin, uint32_t *maybe_end) {
  webp2_option_u32_t end;
  end.is_some = maybe_end != NULL;if (maybe_end) {
    end.val = *maybe_end;
  }
  int32_t option;
  int32_t option1;
  if ((end).is_some) {
    const uint32_t *payload0 = &(end).val;
    option = 1;
    option1 = (int32_t) (*payload0);
  } else {
    option = 0;
    option1 = 0;
  }
  int32_t ret = __wasm_import_webp2_method_uint_8_array_subarray((self).__handle, (int32_t) (begin), option, option1);
  return (webp2_own_uint_8_array_t) { ret };
}

void webp2_method_crypto_get_random_values(webp2_borrow_crypto_t self, webp2_borrow_uint_8_array_t typed_array, webp2_list_u8_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_webp2_method_crypto_get_random_values((self).__handle, (typed_array).__handle, ptr);
  *ret = (webp2_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

webp2_own_crypto_t webp2_get_global_crypto(void) {
  int32_t ret = __wasm_import_webp2_get_global_crypto();
  return (webp2_own_crypto_t) { ret };
}

void webp2_console_log(webp2_string_t *msg) {
  __wasm_import_webp2_console_log((uint8_t *) (*msg).ptr, (*msg).len);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_webp2(void);
__attribute__((used))
void __component_type_object_force_link_webp2_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_webp2();
}
